apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://storage.googleapis.com/helmbucket4'
    targetRevision: x
    chart: FlaskX
  sources: []
  project: default
  syncPolicy:
    automated: null
